#!/usr/bin/env bash

# Having a simple script like this is a bit easier than a multi-package shell.nix
# for doing rapid development.

exec nix-shell -p 'pkgs.haskell.packages.ghc881.ghcWithPackages (p: with p; [
  cabal-install
  vector unordered-containers scientific half
  aeson aeson-pretty
  tasty-quickcheck tasty-hunit quickcheck-instances
  cereal-vector
])' "$@"
